### ISSUE TITLE
如何下载？

### ISSUE THREAD

**Issue by HaoShen2021** [YangChengxxyy/cloudreve_flutter#2]
在releases里没找着啊

**Comment by HaoShen2021** [comment]
<img width="122" alt="image" src="https://user-images.githubusercontent.com/90556839/151533148-717d00af-7399-4c72-94ee-028ec3aefc1c.png">

**Comment by YangChengxxyy** [comment]
还在完善最近应该会发布在release里，稍等等嗷

**Comment by YangChengxxyy** [comment]
最近还在完善，之前release删除了，稍微等等就会发布在release

**Comment by YangChengxxyy** [comment]
### 已发布release测试版本
