### ISSUE TITLE
第一次打开后，关闭无法再次打开。只能清除数据后再打开

### ISSUE THREAD

**Issue by huacong1** [YangChengxxyy/cloudreve_flutter#4]
第一次打开后，关闭程序无法再次正常打开。必须清除数据后才能再次正常打开。

**Comment by YangChengxxyy** [comment]
是你密码改变了吗，我调试都是正常的，是什么版本的后端呢

**Comment by huacong1** [comment]
没有修改密码，手机上安卓12，后端是3.4.2

**Comment by YangChengxxyy** [comment]
> 

控制台有报错吗，可以复现吗

**Comment by huacong1** [comment]
抱歉哈，这几天比较忙没来得及回复。
控制台没报错，第二次进入就卡白屏，无法进入程序。

**Comment by YangChengxxyy** [comment]
每次清楚数据之后重新登录都是如此吗

**Comment by kaaass** [comment]
同样出现此问题。再次打开后停在启动页。日志只有一个 Warn，感觉和问题没有关系：

```
2022-02-27 15:57:02.315 13329-13329/? W/FlutterActivityAndFragmentDelegate: A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
```

**Comment by kaaass** [comment]
反复测试了下，应该是指定其他服务器的问题，使用程序预制的不会发生这个问题。在设置自定义服务器后，再次打开 APP，服务器不会收到任何请求。虽然没有抓包验证，但推测是发送给预制的服务器。

此外，登录时添加第三方服务器后也没有立刻切换。而是需要再次点击切换才能换到设置的服务器。

**Comment by YangChengxxyy** [comment]
> 

大概知道原因了，我最近将会修复

**Comment by huacong1** [comment]
好的，谢谢！
