### ISSUE TITLE
关于域名，

### ISSUE THREAD

**Issue by duck-m** [YangChengxxyy/cloudreve_flutter#5]
添加域名，结尾不能加端口号，可以修复一下吗

**Comment by YangChengxxyy** [comment]
> 添加域名，结尾不能加端口号，可以修复一下吗

自己构建的版本，还是release里的版本呢

**Comment by YangChengxxyy** [comment]
在新版本的中已得到修复 @duck-m

**Comment by duck-m** [comment]
🙏

YangChengxxyy ***@***.***> 于 2022年3月4日周五 23:19写道：
